
name: souq_alwisat
description: سوق الوساط - نزوى الصقرية - تطبيق احترافي
publish_to: 'none'
version: 1.0.0+20
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
